name: "Android flake"
on:
  pull_request:
  push:

permissions:
  contents: write
  
jobs:
  android-build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - uses: cachix/install-nix-action@v25
      with:
        nix_path: nixpkgs=channel:nixos-unstable
        
    - uses: cachix/cachix-action@v14
      with:
        name: mycache
        signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'

    - name: "Decode keystore"
      working-directory: app
      run: |
        echo "${{ secrets.ANDROID_KEYSTORE_BASE64 }}" | base64 --decode > android/release-key.jks

    - name: "Setup key properties"
      working-directory: app
      run: |
        cat <<EOF > android/key.properties
        storePassword=${{ secrets.ANDROID_KEYSTORE_PASSWORD }}
        keyPassword=${{ secrets.ANDROID_KEY_PASSWORD }}
        keyAlias=${{ secrets.ANDROID_KEY_ALIAS }}
        storeFile=release-key.jks
        EOF

    - name: "Build flake"
      run: |
        mkdir -p nix/out/allarch-android
        nix build --option sandbox false --verbose ./nix/android --out-link ./nix/out/allarch-android/result

    - name: "Run flake check"
      run: cd nix/android && nix flake check

    - name: "Copy release files"
      if: startsWith(github.ref, 'refs/tags/')
      run: |
        cp nix/out/allarch-android/result/Notepad_Mono.apk Notepad_Mono-${{ github.ref_name }}-allarch-android.apk
        cp nix/out/allarch-android/result/Notepad_Mono.aab Notepad_Mono-${{ github.ref_name }}-allarch-android.aab

    - name: "Upload release files (apk and aab)"
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v2
      with:
        files: |
          Notepad_Mono-${{ github.ref_name }}-allarch-android.apk
          Notepad_Mono-${{ github.ref_name }}-allarch-android.aab
        overwrite_files: true

    - name: "Success"
      run: echo "Build completed successfully"