name: "Linux flake"
on:
  pull_request:
  push:

permissions:
  contents: write
  
jobs:

  linux-build:
    strategy:
      matrix:
        include:
          - arch: x86_64-linux
            runner: ubuntu-latest
          - arch: arm64-linux
            runner: ubuntu-latest-arm

    steps:
    - name: "Checkout repo"
      uses: actions/checkout@v4
      
    - name: "Init nix"
      uses: cachix/install-nix-action@v25
      with:
        nix_path: nixpkgs=channel:nixos-unstable
        
    - uses: cachix/cachix-action@v14
      with:
        name: mycache
        signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
        
    - name: "Build flake"    
      run: |
        mkdir nix/out
        nix build --option sandbox false --verbose ./nix/allarch-linux --out-link ./nix/out/${{ matrix.arch }}/result

    - name: "Run flake check"
      run: cd nix/allarch-linux && nix flake check

    - name: "Create release archive"
      working-directory: nix/out/${{ matrix.arch }}
      if: startsWith(github.ref, 'refs/tags/')
      run: |
        cp -r result Notepad_Mono-${{ github.ref_name }}-${{ matrix.arch }}
        zip -r ../../../Notepad_Mono-${{ github.ref_name }}-${{ matrix.arch }}.zip Notepad_Mono-${{ github.ref_name }}-${{ matrix.arch }}/*
        rm Notepad_Mono-${{ github.ref_name }}-${{ matrix.arch }}

    - name: "Upload release archive"
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v2
      with:
        files: Notepad_Mono-${{ github.ref_name }}-${{ matrix.arch }}.zip
        overwrite_files: true

    - name: "Success"
      run: echo "Build completed successfully"
