name: "Linux flake"
on:
  pull_request:
  push:

permissions:
  contents: write
  
jobs:
  linux-build:
    runs-on: ubuntu-latest
    steps:
    - name: "Checkout repo"
      uses: actions/checkout@v4
      
    - name: "Init nix"
      uses: cachix/install-nix-action@v25
      with:
        nix_path: nixpkgs=channel:nixos-unstable
        
    - uses: cachix/cachix-action@v14
      with:
        name: mycache
        signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
        
    - name: "Build flake"    
      run: nix build --option sandbox false --verbose ./nix/x86_64-linux --out-link ./nix/x86_64-linux/result

    - name: "Run flake check"
      run: cd nix/x86_64-linux && nix flake check

    - name: "Create release archive"
      working_directory: nix/x86_64-linux/result
      if: startsWith(github.ref, 'refs/tags/')
      run: zip -r ../../../Notepad_Mono-${{ github.ref_name }}-x86_64-linux.zip ./*

    - name: "Upload release archive"
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v2
      with:
        files: Notepad_Mono-${{ github.ref_name }}-x86_64-linux.zip
        overwrite_files: true

    - name: "Success"
      run: echo "Build completed successfully"
