name: "Windows actions"
on:
  pull_request:
  push:
jobs:
  windows-build:
    runs-on: windows-latest
    
    steps:
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: ${{ env.FLUTTER_VERSION }}
        channel: "stable"

    - name: "Download dependencies"
      working-directory: app
      run: flutter pub get

    - name: "Build Windows release"
      working-directory: app
      run: flutter build windows --release
    
    - name: "Success"
      run: echo "Build completed successfully"
