name: "Windows actions"
on:
  pull_request:
  push:

permissions:
  contents: write
  
jobs:
  windows-build:
    runs-on: ${{ matrix.runner }}

    # https://github.com/actions/runner-images
    # https://github.com/actions/partner-runner-images
    strategy:
      matrix:
        include:
          - arch: x86_64-windows
            runner: windows-latest
          - arch: arm64-linux
            runner: windows-11-arm
    
    steps:
    - name: "Checkout repo"
      uses: actions/checkout@v4
      
    - name: "Setup Flutter"
      uses: subosito/flutter-action@v2
      with:
        flutter-version: ${{ env.FLUTTER_VERSION }}
        channel: "stable"

    - name: "Download dependencies"
      working-directory: app
      run: flutter create . && flutter pub get # Later delete flutter create 

    - name: "Build Windows release"
      working-directory: app
      run: flutter build windows --release

    - name: "Copy DLLs"
      working-directory: app
      run: cp windows/lib/* build/windows/x64/runner/Release/

    - name: "Rename executable"
      working-directory: app
      run: mv build/windows/x64/runner/Release/notepad_mono.exe build/windows/x64/runner/Release/NotepadMono.exe

    - name: "Generate MSI executable"
      working-directory: app
      run: dart run msix:create

    - name: "Create release archive"
      if: startsWith(github.ref, 'refs/tags/')
      run: Compress-Archive -Path app/build/windows/x64/runner/Release/* -DestinationPath Notepad_Mono-${{ github.ref_name }}-x86_64-windows.zip
      
    - name: "Upload release archive"
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v2
      with:
        files: Notepad_Mono-${{ github.ref_name }}-x86_64-windows.zip
        overwrite_files: true

    - name: "Success"
      run: echo "Build completed successfully"
